### ISSUE TITLE
CircleCI not uploading binaries

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/erlang-feedstock#1]
Not sure why, but CircleCI is not uploading binaries here. It builds all the way through and even passes its tests. However, it does not try to upload at all.

cc @pelson

**Comment by jakirkham** [comment]
Tried bumping the build number, but no difference. The build seems to be going fine. Not sure why the upload step never happens. Is it confused because there are 2 digits in the major number? Seems like a weird thing, but it is all I can think of here.

**Comment by pelson** [comment]
CircleCI token is defined in their configuration, rather than as a secret in the yaml itself. I double checked the erlang feedstock (https://circleci.com/gh/conda-forge/erlang-feedstock/edit#env-vars) and the token looks fine. 

The stdout from the build doesn't appear to call the upload script, although it looks to be [defined correctly](https://github.com/conda-forge/erlang-feedstock/blob/master/ci_support/run_docker_build.sh#L51).

**Comment by pelson** [comment]
I'm not entirely sure what is wrong with this one - the build log is quite long, but I can't imagine Circle clip the build when the log length is exceeded.

Hmmm

**Comment by jakirkham** [comment]
Yeah, it's very strange.

This is sort of a lazy solution, but could we delete and try to create the feedstock again? It could have the same result, but then again maybe not. Nothing else seems to have had this issue.

**Comment by jakirkham** [comment]
@scopatz, @pelson and I chatted about this briefly today and we are still very puzzled by this. Everything appears setup correctly on the CircleCI end. Everything else we looked at seems ok. There aren't any error messages suggesting the upload failed for some reason. We will keep this in mind. However, we likely won't have time to get to this again until Wednesday when @pelson is back.

**Comment by scopatz** [comment]
Ok, no worries on the timing.  Thanks for looking into it.

**Comment by jakirkham** [comment]
Going to try re-adding it as a feedstock. See this PR ( https://github.com/conda-forge/staged-recipes/pull/566 ). In practice, this doesn't really change anything here (e.g. the recipe doesn't change). However, it will go back through the configuration process and so maybe it will fix something that got screwy. 💫 Then again it could do nothing. It is just something easy to try.

**Comment by jakirkham** [comment]
Weird. That made absolutely no difference. @pelson, any other ideas we could try?

**Comment by scopatz** [comment]
Ugg very strange.

**Comment by pelson** [comment]
Just looked at this in a bit more detail and I imagine it is related to the output being too long (which is weird). It looks like if there is too much output, the next step in the build doesn't get run. I'm experimenting in a ```no_exit``` branch on this feedstock (https://github.com/conda-forge/erlang-feedstock/tree/no_exit).

**Comment by pelson** [comment]
> This is sort of a lazy solution, but could we delete and try to create the feedstock again? It could have the same result, but then again maybe not. Nothing else seems to have had this issue.

That kind of solution only works for Windows 😜 

Looks like it wasn't anything to do with the log length either - it still stops immediately after the build+test (https://circleci.com/gh/conda-forge/erlang-feedstock/12). I guess it could be a sigterm or something from the erlang test. Have you tried removing it?

**Comment by jakirkham** [comment]
> That kind of solution only works for Windows 😜

😆  Hardly.

> Looks like it wasn't anything to do with the log length either - it still stops immediately after the build+test (https://circleci.com/gh/conda-forge/erlang-feedstock/12). I guess it could be a sigterm or something from the erlang test. Have you tried removing it?

I mean it just checks the version. Besides, if there was such a signal, why wouldn't that just crash `conda-build`?

**Comment by pelson** [comment]
@jakirkham - did you ever try running this on a local docker?

**Comment by jakirkham** [comment]
Yep. There are no weird exit codes that I found. I even tried doing this ( https://github.com/conda-forge/erlang-feedstock/pull/7 ), which seems to make no difference AFAICT.

**Comment by jakirkham** [comment]
So, I think the last time we were looking at something related to this we were considering taking out the tests. Should we try this?

**Comment by pelson** [comment]
Didn't we already test this?

**Comment by jakirkham** [comment]
Nope. We noted we should test it after it worked somewhere else. Should be easy enough to try.

**Comment by pelson** [comment]
xref: https://github.com/conda-forge/nco-feedstock/pull/20

**Comment by jakirkham** [comment]
This should be fixed by PR ( https://github.com/conda-forge/erlang-feedstock/pull/15 ).

**Comment by jakirkham** [comment]
Had a bit of a false start, but it seems we have fixed this issue. Linux builds are now available. As it required disabling the tests, went ahead and opened issue ( https://github.com/conda-forge/erlang-feedstock/issues/16 ) to remind us to try and get them working again.
