### ISSUE TITLE
linux aarch64 build

### ISSUE THREAD

**Issue by danielhollas** [conda-forge/erlang-feedstock#154]
### Comment:

Hi! :wave: 

Are there any plans to support linux/aarch64 build? It would help us a lot when installing rabbitmq into Docker containers that can run on the arm64 machines.

**Comment by jakirkham** [comment]
Please follow [these steps]( https://conda-forge.org/docs/maintainer/knowledge_base/#using-arch_rebuildtxt )

**Comment by danielhollas** [comment]
@jakirkham appologies, I am not that familiar with conda-forge processes (but happy to learn!).
Are you suggesting that I open a PR against conda-forge-pinning-feedstock repo and add `erlang` to `arch_rebuild.txt` file?

**Comment by jakirkham** [comment]
Yes
