### ISSUE TITLE
Pin ncurses

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/erlang-feedstock#5]
It appears `ncurses` is not pinned here. We need to pin it. It should be pinned to `5.9*` as shown in the [wiki]( https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies ). 

However, let's hold off on this until the fate of this `ncurses` feedstock PR ( https://github.com/conda-forge/ncurses-feedstock/pull/10 ) is decided. That way, we won't have to rebuild this twice.

**Comment by scopatz** [comment]
Sounds good to me!

**Comment by jakirkham** [comment]
Pinning this in this PR ( https://github.com/conda-forge/erlang-feedstock/pull/6 ).
